In [4]:
import pandas as pd
df = pd.read_excel("data.xlsx")
df

         day  temperature  windspeed  event
0 2020-01-01           32          6   Rain
1 2020-01-02           35          7  Sunny
2 2020-01-03           28          2   Snow

In [5]:
import pandas as pd
df = pd.read_csv("Students.csv")
df

,S.No.,Registration Id,Name,Email,Mobile No
0,1,17991A0518,Ch Surya Mounika,mounika14320@gmail.com,8121330998
1,2,17Q71A0308,Bandaru Ganesh,bandaruganesh11998@gmail.com,7095115119
2,3,17Q71A0315,Gollu Nagendra,nagendragollu123@gmail.com,9703722929
3,4,17Q71A0319,Gullipalli Yaswanth Naidu,yaswanthtony@gmail.com,9154689548
4,5,17Q71A0321,Jami Sai Kumar,jamisaikumar999@gmail.com,8309184015
5,6,17Q71A0344,Peelaramesh,rameshchinna690@gmail.com,9121320900
6,7,17Q71A0346,Pisini Mohan,17q71a0346@aietta.ac.in,9581228561
7,8,17Q71A0352,Seerapu Chandrasekhar,seerapuchandrasekhar189@gmail.com,7799266573
8,9,17Q71A0358,Ummadi Appalaraju,rajuvicky989@gmail.com,9063866510
9,10,17Q71A0501,Adapa Roshini,roshibunny03@gmail.com,9390408305
10,11,17Q71A0503,Adari Jaya Swaroop Kumar,swaroopkumar987@gmail.com,9010028014
11,12,17Q71A0504,Aggunna Pravalika,pravalika.aggunnacsc@gmail.com,9701022380
12,13,17Q71A0505,Prathyusha Allu,prathyusha25.allu@gmail.com,7075934250
13,14,17Q71A0506,Sandilya Aravilli,sandilyaaravalli012@gmail.com,8639613222
14,15,17Q71A0515,Chaganti Bhuvana Chandra,chandu347647@gmail.com,8309445141
15,16,17Q71A0518,Charakam Vikas,charakamvikas2000@gmail.com,7569290647
16,17,17Q71A0520,Chitturi Greeshma Sri,greeshmasri2000@gmail.com,9866953987
17,18,17Q71A0521,Ch.Jayasurya,jayasury63@gmail.com,8247504549
18,19,17Q71A0522,Ch.Vijaya Lakshmi,vijayachukkala09@gmail.com,8367405042
19,20,17Q71A0523,Anisha,anisha16dakavarapu@gmail.com,9652475637
20,21,17Q71A0524,D.Sai Anudeep,anudeepsteyn@gmail.com,9989817514
21,22,17Q71A0527,Doddi Kiran,kiranrocks951@gmail.com,9515099756
22,23,17Q71A0529,Ganetla Laxman Kumar Dev,devdeva789@gmail.com,8297671259
23,24,17Q71A0529,G.Laxman Kumar Dev,devdeva789@gmail.com,8297671259
24,25,17Q71A0530,Gari Vasu,vasugari970@gmail.com,9121061737
25,26,17Q71A0531,Garikina Venu Madhavi,madhu83747@gmail.com,8374751586
26,27,17Q71A0532,Baba Swaroopa,babag442000@gmail.com,9491707319
27,28,17Q71A0534,Jalamana Anilkumar,anilkumarjalamana@gmail.com,7036606842
28,29,17Q71A0535,Kalidindi Anusha,kalidindianusha66@gmail.com,8498067681
29,30,17Q71A0538,K.Rohith,rohith.raxel@gmail.com,9908399779
...,...,...,...,...,...
31,32,17Q71A0540,Kolla Sravani,sravanikolla113@gmail.com,9989406961
32,33,17Q71A0541,Komatlapalli Dhana Sangeetha,sangeethak981@gmail.com,9182605729
33,34,17Q71A0543,Kothakota Manikanta,kothakotamanikanta1999@gmail.com,9704926910
34,35,17Q71A0545,Lenkachaitanya,lenkachaitanya427@gmail.com,9603325180
35,36,17Q71A0547,Majji Kalyan,kalyanmajji66@gmail.com,9642834844
36,37,17Q71A0548,Maradana Anusha,anushamaradana771@gmail.com,8498968771
37,38,17Q71A0549,Ramya,ramyamarrapu2000@gmail.com,9177560853
38,39,17Q71A0550,Meghana Yeturi,yeturi.maggie28@gmail.com,8466084105
39,40,17Q71A0551,M Ravindra,ravindrameraka@gmail.com,9347394952
40,41,17Q71A0552,M.Sai Manohar,manoharmiriyala123@gmail.com,9553992043
41,42,17Q71A0553,M.Sneha,snehamirtivada@gmail.com,8328494623
42,43,17Q71A0554,Moyyi Appalanaidu,moyyiappalanaidu143@gmail.com,7036158676
43,44,17Q71A0556,Nammi Yamini,nammiyamini@gmail.com,9121730248
44,45,17Q71A0560,Nikkala Chakradhar,chakri.nikki2000@gmail.com,9182528383
45,46,17Q71A0561,N.Sirisha,siri.05072000@gmail.com,7032318845
46,47,17Q71A0566,Panigrahi Suresh,sureshdreamz123@gmail.com,9502727749
47,48,17Q71A0568,Satish Patnala,psatyaaa143@gmail.com,7993075119
48,49,17Q71A0569,Pedakota Kumar Sai,pedakotakumar404@gmail.com,9010848512
49,50,17Q71A0570,Pilla Neelima,neelimaneha22@gmail.com,9515575058
50,51,17Q71A0577,Pudu Sandhya,pudusandhya@gmail.com,7981119222
51,52,17Q71A0582,Rongali Sridevi,sridevi06533@gmail.com,7013524583
52,53,17Q71A0585,Saladhi.Deeksha,deeksha.saladi1@gmail.com,7036530391
53,54,17Q71A0590,Sowdala.Meghana,sowdalameghana90@gmail.com,9949587763
54,55,17Q71A0592,T. Kavya Sai,kavyasaitammina@gmail.com,9666515871
55,56,17Q71A0593,T Neelakanta,neelakanta300@gmail.com,7659822230
56,57,17Q71A0595,Thene Dhanasai,dhanasaithene@gmail.com,9014314460
57,58,17Q71A0596,Thotakura Gopi,tgopi2110@gmail.com,7995388368
58,59,17Q71A0599,V. Soorya Dev,sooryadevvobhilineni@gmail.com,9959030864
59,60,17Q71AO533,G.Sai Kalyani,gundakalyani11@gmail.com,7416501892
60,61,18Q75AO305,Baditha Bhanuprasad,bhanuprasad074@gmail.com,9133616097

In [7]:
weather_data={
    'day':['1/1/2020','2/1/2020','3/1/2020','4/1/2020','5/1/2020'],
    'temperature':[32,35,28,24,32],
    'windspeed':[5,6,7,8,9],
    'event':['rain','sunny','snow','rain','feffe']
}
df=pd.DataFrame(weather_data) # here passing a dictionary as a argument(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2020           32          5   rain
1  2/1/2020           35          6  sunny
2  3/1/2020           28          7   snow
3  4/1/2020           24          8   rain
4  5/1/2020           32          9  feffe

In [13]:
#here create a dataframe using list of tuples
weather=[
    ('1/1/2020',32,6,'rain'),
    ('2/1/2020',35,2,'sunny'),
    ('3/1/2020',38,9,'winter')
]
df=pd.DataFrame(weather_data,columns=["day","temperature","windspeed","event"])
df

        day  temperature  windspeed  event
0  1/1/2020           32          5   rain
1  2/1/2020           35          6  sunny
2  3/1/2020           28          7   snow
3  4/1/2020           24          8   rain
4  5/1/2020           32          9  feffe

In [14]:
#list of dictionaries
weather1=[
    {'day':'1/1/2020','temperature':32,'windspeed':6,'event':'rain'},
    {'day':'2/1/2020','temperature':36,'windspeed':9,'event':'Sunny'},
    {'day':'1/1/2020','temperature':32,'windspeed':6,'event':'snow'}
]
df=pd.DataFrame(weather1)
df

        day  event  temperature  windspeed
0  1/1/2020   rain           32          6
1  2/1/2020  Sunny           36          9
2  1/1/2020   snow           32          6